apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-java-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-java-webapp
  template:
    metadata:
      labels:
        app: my-java-webapp
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: my-java-webapp
          image: docker-repo.sk-devops.com/puneeth_nexus_push/my-java-webapp:v27
          ports:
            - containerPort: 8080
