apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-java-webapp
  labels:
    app: my-java-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-java-webapp
  template:
    metadata:
      labels:
        app: my-java-webapp
    spec:
      containers:
        - name: my-java-webapp
          image: puneethuserdoc/my-java-webapp:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
