apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-java-webapp
  labels:
    app: my-java-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-java-webapp
  template:
    metadata:
      labels:
        app: my-java-webapp
    spec:
      imagePullSecrets:
        - name: my-registry-secret
      containers:
        - name: my-java-webapp
          image: puneethuserdoc/my-java-webapp:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: my-java-webapp-service
spec:
  type: LoadBalancer
  selector:
    app: my-java-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
