apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-java-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-java-webapp
  template:
    metadata:
      labels:
        app: my-java-webapp
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: my-java-webapp
          image: nexus.sk-devops.com:8082/docker-sk-devops/my-java-webapp:latest
          ports:
            - containerPort: 8080
